# Generated by Django 3.2.5 on 2021-08-01 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름없음', max_length=255, verbose_name='이름')),
                ('text', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름없음', max_length=255, verbose_name='이름')),
                ('text', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.comment', verbose_name='대상댓글')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('text', models.TextField(verbose_name='본문')),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개')),
                ('description', models.TextField(max_length=130, verbose_name='게시글설명')),
                ('keywords', models.CharField(default='게시글의키워드', max_length=255, verbose_name='게시글의키워드')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='갱신일')),
                ('relation_posts', models.ManyToManyField(blank=True, related_name='_search_post_relation_posts_+', to='search.Post', verbose_name='관련기사')),
                ('tags', models.ManyToManyField(blank=True, to='search.Tag', verbose_name='태그')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.post', verbose_name='대상게시글'),
        ),
    ]
