# Generated by Django 3.2.5 on 2021-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumnbail',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='썸네일'),
        ),
    ]
