# Generated by Django 3.2.5 on 2021-08-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210801_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumnbail',
            new_name='thumbnail',
        ),
    ]
